version = 1

[install]
clang-tools.pkg-path = "clang-tools"
gcc.pkg-path = "gcc"
gdb.pkg-path = "gdb"
gnumake.pkg-path = "gnumake"
help2man.pkg-path = "help2man"

[build.t3]
sandbox = "pure"
runtime-packages = []
version.command = "git describe --tags --always --dirty"
description = "Next generation tee with colorized output streams and precise time stamping"
command = '''
  make
  make test
  make install PREFIX=$out
'''
